// <auto-generated />
using System;
using Botana;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Botana.Migrations
{
    [DbContext(typeof(RPGContext))]
    partial class RPGModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Botana.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GameMaster");

                    b.Property<string>("GameName");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Botana.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameId");

                    b.Property<string>("PlayerName");

                    b.Property<int?>("SheetId");

                    b.HasKey("PlayerId");

                    b.HasIndex("GameId");

                    b.HasIndex("SheetId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Botana.Sheet", b =>
                {
                    b.Property<int>("SheetId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("SheetId");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("Botana.Stats", b =>
                {
                    b.Property<int>("StatsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("SheetId");

                    b.Property<int>("Value");

                    b.HasKey("StatsId");

                    b.HasIndex("SheetId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("Botana.Player", b =>
                {
                    b.HasOne("Botana.Game")
                        .WithMany("GamePlayer")
                        .HasForeignKey("GameId");

                    b.HasOne("Botana.Sheet", "Sheet")
                        .WithMany()
                        .HasForeignKey("SheetId");
                });

            modelBuilder.Entity("Botana.Stats", b =>
                {
                    b.HasOne("Botana.Sheet")
                        .WithMany("PlayerStats")
                        .HasForeignKey("SheetId");
                });
#pragma warning restore 612, 618
        }
    }
}
